#!/bin/bash

set -e

WORKSPACE=/var/lib/go-agent/pipelines/newtest
if sudo docker ps -a | grep -i mynewtest; then
   sudo docker cp $WORKSPACE/npmdocker/test.sh  mynewtest:/opt/
   sudo docker cp $WORKSPACE/facilities/src/external/facilities  mynewtest:/opt/
   sudo docker exec -i mynewtest /bin/bash /opt/test.sh
else
   sudo docker build -t bj/nodejs:7.10.0  $WORKSPACE/npmdocker/
   sudo docker run -d --name mynewtest bj/nodejs:7.10.0
   sudo docker cp $WORKSPACE/facilities/src/external/facilities  mynewtest:/opt/
   sudo docker exec -i mynewtest /bin/bash /opt/test.sh

fi


if sudo docker images |grep none ; then
   sudo docker images |grep none |awk '{print $3}' | sudo xargs docker rmi -f
fi

if [ ! -d "$WORKSPACE/wlbuild" ];then
    sudo mkdir -pv $WORKSPACE/wlbuild
    sudo chown -R go:go $WORKSPACE/wlbuild
else
    sudo rm -rf $WORKSPACE/wlbuild
    sudo mkdir -pv $WORKSPACE/wlbuild
fi

sudo docker cp   mynewtest:/opt/facilities/build $WORKSPACE/wlbuild/


exec "$@"
